version: '3.3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysqldb:5.7
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=kaddem
      - MYSQL_ALLOW_EMPTY_PASSWORD= yes
    ports:
      - "3306:3306"
  springboot:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - "8089:8089"
    stdin_open: true
    tty: true
    container_name: projetKadem